theme: jekyll-theme-cayman
title: EXA_PMRA20 : International workshop on Performance modelling, Runtime System and Applications at the Exascale 
description: To be held in conjunction with ICPP2020 - The 49th International Conference on Parallel Processing
show_downloads: false
github:
  is_project_page: false
